added new module
CortesWD/dwfe-suma-01-exce pull request #2
Opened 2021-08-10 23:44 UTC by marioalejandropz

Added mario module

2021-08-10 23:45 UTC, CortesWD requested changes

2021-08-10 23:45 UTC, CortesWD commented on js/modules/mario.js
> +console.log("Hello");
falta crear el objeto persona con tus datos.

2021-08-11 00:09 UTC, CortesWD requested changes

2021-08-11 00:09 UTC, CortesWD commented on js/constructor/Person.js
> +      this.photo =
esto no va aqui :)

2021-08-11 00:09 UTC, CortesWD commented on js/constructor/Person.js
> +         "https://instagram.feoh6-1.fna.fbcdn.net/v/t51.2885-19/s320x320/20759655_308051336333648_8795388870909755392_a.jpg?_nc_ht=instagram.feoh6-1.fna.fbcdn.net&_nc_ohc=m8HjD3uT2cwAX8rGIHQ&tn=n3zaU
esto no va aqui :)

2021-08-11 00:09 UTC, CortesWD commented on js/constructor/Person.js
> +      this.name = "Mario";
esto no va aqui :)

2021-08-11 01:01 UTC, CortesWD requested changes

2021-08-11 01:01 UTC, CortesWD commented on js/index.js
> +import mario from "./js/modules/mario.js";
js al principo del path sobra.

2021-08-11 01:50 UTC, CortesWD approved these changes

2021-08-11 01:52 UTC, abdulflorez approved these changes

2021-08-11 01:54 UTC, merged